
name: Test dataset compliance
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  compliance:
    uses: courtois-neuromod/actions-template/.github/workflows/compliance.yml@main
